name: arm
on:
  push:
    paths:
      - '.github/workflows/arm.yml'
jobs:
  test:
    runs-on: windows-11-arm
    steps:
      - uses: actions/checkout@v4
        with:
          path: bee.lua
          repository: actboy168/bee.lua
          submodules : recursive
      - uses: actboy168/setup-luamake@master
      - run: |
          cd bee.lua
          luamake.exe
