name: arm
on:
  push:
    paths:
      - '.github/workflows/arm.yml'
jobs:
  test:
    runs-on: windows-11-arm
    steps:
      - uses: actboy168/setup-lua@master
        with:
          luaVersion: '5.4'
      - uses: actions/checkout@v4
        with:
          path: luamake
          repository: actboy168/luamake
          submodules : recursive
      - run: |
          cd luamake
          lua test.lua
          .\compile\build.bat
