name: CI
on: [ push ]
jobs:
  openbsd:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
        with:
          path: luamake
          repository: actboy168/luamake
      - uses: actions/checkout@v3
        with:
          path: bee.lua
          repository: actboy168/bee.lua
          submodules : recursive
      - uses: vmactions/openbsd-vm@v0
        with:
          usesh: true
          prepare: |
            pkg_add gcc-11.2.0p3 ninja libinotify
          run: |
            egcc --version
