name: CI
on: [ push ]
jobs:
  linux-arm:
    runs-on: ubuntu-latest
    steps:
      - uses: uraimo/run-on-arch-action@v2
        with:
          arch: armv7
          distro: ubuntu20.04
          dockerRunArgs: |
            --volume "${PWD}:/actboy168"
          run: |
            uname -m
