name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          repository: actboy168/bee.lua
      - uses: actboy168/setup-luamake@master
      - run: sudo apt-get update
      - run: sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
      - run: luamake -cc aarch64-linux-gnu-gcc
