name: CI
on: [ push ]
jobs:
  linux-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: actboy168/luamake
          submodules : recursive
      - uses: actions/checkout@v3
        with:
          path: json.lua
          repository: actboy168/json.lua
          submodules : recursive
      - uses: uraimo/run-on-arch-action@v2
        with:
          arch: armv7
          distro: ubuntu20.04
          dockerRunArgs: |
            --volume "${PWD}:/actboy168"
          install: |
            apk update
            apk add gcc g++ ninja
          run: |
            ./compile/build.sh notest
            cd json.lua
            ./../luamake lua test/conformance.lua
