name: CI
on: [ push ]
jobs:
  compile:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-20.04,   target: linux,   platform: linux-x64,   container: 'ubuntu:18.04' }
          - { os: ubuntu-20.04,   target: linux,   platform: linux-arm64, container: 'ubuntu:18.04' }
    runs-on: ${{ matrix.os }}
    container:
      image: ${{ matrix.container }}
    steps:
      - name: Prepare container
        if: ${{ matrix.target == 'linux' }}
        run: |
          apt-get update
          apt-get install -y software-properties-common
          add-apt-repository -y ppa:ubuntu-toolchain-r/test # For gcc-9 and g++-9
          add-apt-repository -y ppa:git-core/ppa # For git>=2.18.
          update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 100
          update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 100
          apt-get update
          apt-get install -y sudo git
      - name: Install gcc
        if: ${{ matrix.platform == 'linux-x64' }}
        run: |
          apt-get install -y gcc-9 g++-9
      - name: Install gcc
        if: ${{ matrix.platform == 'linux-arm64' }}
        run: |
          apt-get install -y gcc-9-aarch64-linux-gnu g++-9-aarch64-linux-gnu

      - uses: actions/checkout@v3
        with:
          repository: actboy168/bee.lua
          submodules: recursive
      - uses: actboy168/setup-luamake@master
      - run: luamake

