name: CI
on: [ push ]
jobs:
  linux-arm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: actboy168/luamake
          submodules : recursive
      - uses: uraimo/run-on-arch-action@v2
        with:
          arch: armv6
          distro: alpine_latest
          dockerRunArgs: |
            --volume "${PWD}:/actboy168"
          install: |
            apk update
            apk upgrade
            apk add gcc g++ ninja
          run: |
            gcc --version
            ./compile/build.sh notest
