name: CI
on: [ push ]
jobs:
  freebsd:
    runs-on: macos-12
    steps:
      - run: |
          echo "RUNNER_OS: $RUNNER_OS"
          echo "RUNNER_ARCH: $RUNNER_ARCH"
          echo "RUNNER_NAME: $RUNNER_NAME"
      - uses: actions/checkout@v3
        with:
          path: luamake
          repository: actboy168/luamake
          submodules : recursive
      - uses: actions/checkout@v3
        with:
          path: bee.lua
          repository: actboy168/bee.lua
          submodules : recursive
      - uses: vmactions/freebsd-vm@v0
        with:
          usesh: true
          prepare: |
            pkg install -y gcc ninja libinotify
          run: |
            cd luamake
            ./compile/build.sh
            cd ../bee.lua
            ./../luamake/luamake
  openbsd:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
        with:
          path: luamake
          repository: actboy168/luamake
          submodules : recursive
      - uses: actions/checkout@v3
        with:
          path: bee.lua
          repository: actboy168/bee.lua
          submodules : recursive
      - uses: vmactions/openbsd-vm@v0
        with:
          usesh: true
          prepare: |
            pkg_add ninja libinotify
          run: |
            gcc --version
            cd luamake
            ./compile/build.sh
            cd ../bee.lua
            ./../luamake/luamake
  netbsd:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
        with:
          path: luamake
          repository: actboy168/luamake
          submodules : recursive
      - uses: actions/checkout@v3
        with:
          path: bee.lua
          repository: actboy168/bee.lua
          submodules : recursive
      - uses: vmactions/netbsd-vm@v0
        with:
          usesh: true
          prepare: |
            pkg_add ninja libinotify
          run: |
            gcc --version
            cd luamake
            ./compile/build.sh
            cd ../bee.lua
            ./../luamake/luamake
