name: CI
on: [ push ]
jobs:
  netbsd:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
        with:
          path: luamake
          repository: actboy168/luamake
          submodules : recursive
      - uses: actions/checkout@v3
        with:
          path: bee.lua
          repository: actboy168/bee.lua
      - uses: vmactions/netbsd-vm@v0
        with:
          usesh: true
          prepare: |
            pkg_add gcc10 ninja libinotify
          run: |
            gcc --version
