name: CI
on: [ push ]
jobs:
  openbsd:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
        with:
          path: luamake
          repository: actboy168/luamake
      - uses: actions/checkout@v3
        with:
          path: bee.lua
          repository: actboy168/bee.lua
          submodules : recursive
      - uses: vmactions/openbsd-vm@v0
        with:
          usesh: true
          prepare: |
            pkg_add gcc ninja libinotify
          run: |
            gcc --version
