name: CI
on: [ push ]
jobs:
  windows-mingw:
    runs-on: windows-latest
    steps:
      - uses: actboy168/setup-luamake@master
      - uses: actions/checkout@v3
        with:
          repository: actboy168/bee.lua
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-ninja
      - shell: msys2 {0}
        run: |
          luamake
