name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actboy168/setup-luamake@master
      - uses: actions/checkout@v3
        with:
          repository: actboy168/bee.lua
      - run: luamake
