name: CI
on:
  push:
    paths:
      - '.github/workflows/bsd.yml'
jobs:
  freebsd:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
        with:
          path: luamake
          repository: actboy168/luamake
          submodules : recursive
      - uses: actions/checkout@v3
        with:
          path: bee.lua
          repository: actboy168/bee.lua
          submodules : recursive
      - uses: vmactions/freebsd-vm@v0
        with:
          usesh: true
          prepare: |
            pkg install -y ninja libinotify
          run: |
            cd luamake
            ./compile/build.sh notest
            cd ../bee.lua
            ./../luamake/luamake -notest
            ./build/bin/bootstrap test/test.lua -v
  openbsd:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
        with:
          path: luamake
          repository: actboy168/luamake
          submodules : recursive
      - uses: actions/checkout@v3
        with:
          path: bee.lua
          repository: actboy168/bee.lua
          submodules : recursive
      - uses: vmactions/openbsd-vm@v0
        with:
          usesh: true
          prepare: |
            pkg_add ninja libinotify
          run: |
            cd luamake
            ./compile/build.sh notest
            cd ../bee.lua
            ./../luamake/luamake -notest
            ./build/bin/bootstrap test/test.lua -v
  netbsd:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
        with:
          path: luamake
          repository: actboy168/luamake
          submodules : recursive
      - uses: actions/checkout@v3
        with:
          path: bee.lua
          repository: actboy168/bee.lua
          submodules : recursive
      - uses: vmactions/netbsd-vm@v0
        with:
          usesh: true
          prepare: |
            pkg_add ninja libinotify
          run: |
            cd luamake
            ./compile/build.sh notest
            cd ../bee.lua
            ./../luamake/luamake -notest
            ./build/bin/bootstrap test/test.lua -v
