name: freebsd
on:
  push:
    paths:
      - '.github/workflows/freebsd.yml'
jobs:
  freebsd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: luamake
          repository: actboy168/luamake
          submodules : recursive
      - uses: actions/checkout@v4
        with:
          path: bee.lua
          repository: actboy168/bee.lua
          submodules : recursive
      - uses: cross-platform-actions/action@v0.23.0
        with:
          operating_system: freebsd
          version: '14.0'
          run: |
            sudo pkg install -y ninja libinotify
            cd luamake
            ./compile/build.sh notest
            cd ../bee.lua
            ./../luamake/luamake -notest
            ./build/bin/bootstrap test/test.lua -v
