name: openbsd
on:
  push:
    paths:
      - '.github/workflows/openbsd.yml'
jobs:
  openbsd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: luamake
          repository: actboy168/luamake
          submodules : recursive
      - uses: actions/checkout@v4
        with:
          path: bee.lua
          repository: actboy168/bee.lua
          submodules : recursive
      - uses: cross-platform-actions/action@v0.24.0
        with:
          operating_system: openbsd
          version: '7.5'
          run: |
            sudo pkg_add ninja libinotify
            cd luamake
            ./compile/build.sh notest
            cd ../bee.lua
            ./../luamake/luamake -notest
            ./build/bin/bootstrap test/test.lua -v
