name: test
on:
  push:
    paths:
      - '.github/workflows/test.yml'
jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        arch: [armv7, riscv64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: actboy168/bee.lua
      - uses: actions/checkout@v3
        with:
          path: luamake
          repository: actboy168/luamake
          submodules : recursive
      - uses: uraimo/run-on-arch-action@v2
        with:
          arch: ${{ matrix.arch }}
          distro: ubuntu20.04
          dockerRunArgs: |
            --volume "${PWD}:/actboy168"
          install: |
            apt-get update -q -y
            apt-get install -q -y gcc g++ ninja-build
          run: |
            pushd luamake
            ./compile/build.sh notest
            popd
            ./luamake/luamake -mode debug -notest
            ./build/bin/bootstrap test/test.lua -v
